[project]
name = "elevate-labs-python-day-06"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "pymongo>=4.13.2",
]
